from enum import StrEnum

__all__ = ('EventType',)


class EventType(StrEnum):
    LATE_DELIVERY_VOUCHERS = 'LATE_DELIVERY_VOUCHERS'
    WRITE_OFFS = 'WRITE_OFFS'
    DELIVERY_SPEED = 'DELIVERY_SPEED'
    STOPS_AND_RESUMES = 'STOPS_AND_RESUMES'
    CANCELED_ORDERS = 'CANCELED_ORDERS'
    REVENUE_STATISTICS = 'REVENUE_STATISTICS'
    CHEATED_PHONE_NUMBERS = 'CHEATED_PHONE_NUMBERS'
    INGREDIENTS_STOP_SALES = 'INGREDIENTS_STOP_SALES'
