from enum import StrEnum

__all__ = ('EventType',)


class EventType(StrEnum):
    LATE_DELIVERY_VOUCHERS = 'LATE_DELIVERY_VOUCHERS'
    WRITE_OFFS = 'WRITE_OFFS'
    DELIVERY_SPEED = 'DELIVERY_SPEED'
    INVENTORY_STOCKS = 'INVENTORY_STOCKS'
    CANCELED_ORDERS = 'CANCELED_ORDERS'
    SALES_STATISTICS = 'SALES_STATISTICS'
    CHEATED_PHONE_NUMBERS = 'CHEATED_PHONE_NUMBERS'
    INGREDIENTS_STOP_SALES = 'INGREDIENTS_STOP_SALES'
    SECTOR_STOP_SALES = 'SECTOR_STOP_SALES'
    PIZZERIA_STOP_SALES = 'PIZZERIA_STOP_SALES'
    UNPRINTED_RECEIPTS = 'UNPRINTED_RECEIPTS'
    HEATED_SHELF_STATISTICS = 'HEATED_SHELF_STATISTICS'
    FEEDBACKS = 'FEEDBACKS'
